name: local_service_finder
description: "Local Service Finder"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6

  # use for database
  firebase_auth: ^4.19.2
  firebase_core: ^2.30.0
  firebase_messaging: ^14.8.2
  cloud_firestore: ^4.17.0

  # use for statemanagement
  provider: ^6.1.2

  # use for api
  http: ^1.2.1

  # use for awesome icons
  iconsax: ^0.0.8

  # use for bed or ok message
  fluttertoast: ^8.2.6

  # use for pick image to camera and gallery
  image_picker: ^1.1.0

  # use for circular indicator
  flutter_spinkit: ^5.2.1

  # use for fonts
  google_fonts: ^6.2.1
  cached_network_image: ^3.3.1
  uuid: ^4.4.0
  flutter_rating_bar: ^4.0.1
  google_maps_flutter: ^2.2.8
  location: ^7.0.0
  permission_handler: ^11.3.1
  multi_dropdown: ^2.1.4
  geolocator: ^11.0.0
  firebase_storage: ^11.7.5
  intl: ^0.19.0
  flutter_local_notifications: ^17.1.2
  custom_info_window: ^1.0.1
  easypaisa_flutter: ^1.0.3
  shared_preferences: ^2.3.2
  flutter_timer_countdown: ^1.0.7
  flutter_screenutil: ^5.9.3
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: "^0.13.1"
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo.png"
  min_sdk_android: 21


flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/logo/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
