// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUHkZ12UPA4KVYPD5S2v483IR7jwgUjk8',
    appId: '1:107821034688:web:1a6c802d0eae8166361125',
    messagingSenderId: '107821034688',
    projectId: 'local-service-finder-415e4',
    authDomain: 'local-service-finder-415e4.firebaseapp.com',
    storageBucket: 'local-service-finder-415e4.appspot.com',
    measurementId: 'G-6L0HZB95CL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZmazUt3G-38TL3R-MdExnK4i3jSS0gWI',
    appId: '1:948146212552:android:1d7ce89d04bb5c4d725ffd',
    messagingSenderId: '948146212552',
    projectId: 'local-service-finder-24fe3',
    storageBucket: 'local-service-finder-24fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArA1L5JOMkfpdq40Pk-GFyJ_1TMA6WiSY',
    appId: '1:948146212552:ios:279733ac652d2ac3725ffd',
    messagingSenderId: '948146212552',
    projectId: 'local-service-finder-24fe3',
    storageBucket: 'local-service-finder-24fe3.appspot.com',
    iosBundleId: 'com.example.localServiceFinder',
  );

}